---
swagger: "2.0"
info:
  version: "0.0.2"
  title: "Optimization framework service"
  license:
    name: "Apache"
host: "192.168.99.100:8080"
basePath: "/v1"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /models:
    get:
      tags:
      - "models"
      summary: "Fetches all installed models in the framework"
      description: ""
      operationId: "get_models_in"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Model_answer"
        400:
          description: "Bad request"
        405:
          description: "Invalid input"
        500:
          description: "Internal server error"
      x-swagger-router-controller: "swagger_server.controllers.models_controller"
  /models/upload/{name}:
    post:
      tags:
      - "models"
      summary: "Mathematical model for the optimization solver"
      description: ""
      operationId: "optimization_model"
      consumes:
      - "text/plain"
      parameters:
      - name: "name"
        in: "path"
        description: "Name of the loaded model"
        required: true
        type: "string"
      - in: "body"
        name: "upModel"
        description: "Mathematical model that needs to be added to the optimization\
          \ framework"
        required: true
        schema:
          $ref: "#/definitions/Model"
      responses:
        200:
          description: "OK"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.models_controller"
  /models/upload/url:
    post:
      tags:
      - "models"
      summary: "Url for the mathematical model for the optimization solver"
      description: ""
      operationId: "optimization_model_url"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "upModelUrl"
        description: "Url of the mathematical model that needs to be added to the\
          \ optimization framework"
        required: true
        schema:
          $ref: "#/definitions/Model_url"
      responses:
        200:
          description: "OK"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.models_controller"
  /registry/input/:
    post:
      tags:
      - "registry"
      summary: "Creates a new data source as input"
      description: ""
      operationId: "input_source"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Input_Source"
        description: "Data source to be created"
        required: true
        schema:
          $ref: "#/definitions/InputSource"
      responses:
        201:
          description: "Created succesfully"
        400:
          description: "Bad request"
        405:
          description: "Invalid input"
        500:
          description: "Internal server error"
      x-swagger-router-controller: "swagger_server.controllers.registry_controller"
  /registry/output/:
    post:
      tags:
      - "registry"
      summary: "Creates a new data source as ouput"
      description: ""
      operationId: "output_source"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Output_Source"
        description: "Output data source to be created"
        required: true
        schema:
          $ref: "#/definitions/OutputSource"
      responses:
        200:
          description: "Created succesfully"
        400:
          description: "Bad request"
        405:
          description: "Invalid input"
        500:
          description: "Internal server error"
      x-swagger-router-controller: "swagger_server.controllers.registry_controller"
  /data/{id}:
    get:
      tags:
      - "data"
      summary: "Receives data from the framework"
      description: ""
      operationId: "get_data_in"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the data source"
        required: true
        type: "string"
      - in: "body"
        name: "dataset"
        description: "Dataset submitted to the framework"
        required: false
        schema:
          $ref: "#/definitions/dataset"
      responses:
        200:
          description: "Created succesfully"
        400:
          description: "Bad request"
        405:
          description: "Invalid input"
        500:
          description: "Internal server error"
      x-swagger-router-controller: "swagger_server.controllers.data_controller"
  /data/load/{id}:
    post:
      tags:
      - "data"
      summary: "Submits load data to the framework"
      description: ""
      operationId: "load_data_in"
      consumes:
      - "application/json"
      - "text/plain"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the data source"
        required: true
        type: "string"
      - in: "body"
        name: "dataset"
        description: "Dataset submitted to the framework"
        required: false
        schema:
          type: "object"
      responses:
        200:
          description: "Created succesfully"
        400:
          description: "Bad request"
        405:
          description: "Invalid input"
        500:
          description: "Internal server error"
      x-swagger-router-controller: "swagger_server.controllers.data_controller"
  /data/pv/{id}:
    post:
      tags:
      - "data"
      summary: "Submits PV data to the framework"
      description: ""
      operationId: "pv_data_in"
      consumes:
      - "application/json"
      - "text/plain"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the data source"
        required: true
        type: "string"
      - in: "body"
        name: "dataset"
        description: "Dataset submitted to the framework"
        required: false
        schema:
          type: "object"
      responses:
        200:
          description: "Created succesfully"
        400:
          description: "Bad request"
        405:
          description: "Invalid input"
        500:
          description: "Internal server error"
      x-swagger-router-controller: "swagger_server.controllers.data_controller"
  /command/start:
    put:
      tags:
      - "command"
      summary: "Command for starting the framework"
      description: ""
      operationId: "framework_start"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "startOFW"
        description: "Start command for the optimization framework \n repetitions:\
          \ -1 infinite repetitions"
        required: true
        schema:
          $ref: "#/definitions/Start"
      responses:
        200:
          description: "OK"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.command_controller"
  /command/stop:
    put:
      tags:
      - "command"
      summary: "Command for stoping the framework"
      description: ""
      operationId: "framework_stop"
      consumes:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.command_controller"
definitions:
  Start:
    type: "object"
    required:
    - "horizon"
    - "repetition"
    - "time_step"
    properties:
      repetition:
        type: "integer"
        format: "int32"
      time_step:
        type: "integer"
        format: "int32"
      horizon:
        type: "integer"
        format: "int32"
      model_name:
        type: "string"
      solver:
        type: "string"
    example:
      time_step: 6
      horizon: 1
      model_name: "model_name"
      repetition: 0
      solver: "solver"
  Load:
    type: "object"
    required:
    - "Internal_Forecast"
    - "P_Load"
    properties:
      Internal_Forecast:
        type: "boolean"
        description: "Is it forecasted data? Or row data"
      P_Load:
        $ref: "#/definitions/Source"
      Q_Load:
        $ref: "#/definitions/Source"
      meta:
        $ref: "#/definitions/metaLoad"
    example:
      Internal_Forecast: true
      Q_Load:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
      meta:
        pf_Load: 6.02745629999999987802539180847816169261932373046875
      P_Load:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
  metaLoad:
    type: "object"
    properties:
      pf_Load:
        type: "number"
        format: "float"
    example:
      pf_Load: 6.02745629999999987802539180847816169261932373046875
  PV:
    type: "object"
    required:
    - "Internal_Forecast"
    - "P_PV"
    properties:
      Internal_Forecast:
        type: "boolean"
        description: "Is it forecasted data? Or row data"
      P_PV:
        $ref: "#/definitions/Source"
      meta:
        $ref: "#/definitions/metaPV"
    description: "Definition of a PV element as input for the optimizer"
    example:
      Internal_Forecast: true
      P_PV:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
      meta:
        PV_Inv_Max_Power: 1
  PV_Output:
    type: "object"
    required:
    - "P_PV_Output"
    properties:
      P_PV_Output:
        $ref: "#/definitions/Source"
      Q_PV_Output:
        $ref: "#/definitions/Source"
    example:
      Q_PV_Output:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
      P_PV_Output:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
  metaPV:
    type: "object"
    properties:
      PV_Inv_Max_Power:
        type: "integer"
        format: "int32"
    example:
      PV_Inv_Max_Power: 1
  ESS:
    type: "object"
    required:
    - "SoC_Value"
    properties:
      SoC_Value:
        $ref: "#/definitions/SourceESS"
      meta:
        $ref: "#/definitions/metaESS"
    example:
      SoC_Value:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
        value_percent: 59
      meta:
        ESS_Max_Discharge_Power: 3.61607669999999981058635967201553285121917724609375
        ESS_Max_SoC: 2.30213599999999996015276337857358157634735107421875
        ESS_Charging_Eff: 2.027123000000000008213874025386758148670196533203125
        ESS_Min_SoC: 5.63737699999999986033571985899470746517181396484375
        ESS_Max_Charge_Power: 9.301444000000000045247361413203179836273193359375
        ESS_Discharging_Eff: 4.14560800000000018172841009800322353839874267578125
        ESS_Capacity: 7.06140140000000027242776923230849206447601318359375
  ESS_Output:
    type: "object"
    required:
    - "P_ESS_Output"
    properties:
      P_ESS_Output:
        description: "Setting power of the ESS"
        $ref: "#/definitions/Source"
    example:
      P_ESS_Output:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
  metaESS:
    type: "object"
    properties:
      ESS_Min_SoC:
        type: "number"
        format: "float"
      ESS_Max_SoC:
        type: "number"
        format: "float"
      ESS_Capacity:
        type: "number"
        format: "float"
      ESS_Max_Charge_Power:
        type: "number"
        format: "float"
      ESS_Max_Discharge_Power:
        type: "number"
        format: "float"
      ESS_Charging_Eff:
        type: "number"
        format: "float"
      ESS_Discharging_Eff:
        type: "number"
        format: "float"
    example:
      ESS_Max_Discharge_Power: 3.61607669999999981058635967201553285121917724609375
      ESS_Max_SoC: 2.30213599999999996015276337857358157634735107421875
      ESS_Charging_Eff: 2.027123000000000008213874025386758148670196533203125
      ESS_Min_SoC: 5.63737699999999986033571985899470746517181396484375
      ESS_Max_Charge_Power: 9.301444000000000045247361413203179836273193359375
      ESS_Discharging_Eff: 4.14560800000000018172841009800322353839874267578125
      ESS_Capacity: 7.06140140000000027242776923230849206447601318359375
  grid:
    type: "object"
    properties:
      meta:
        $ref: "#/definitions/metaGrid"
    example:
      meta:
        Q_Grid_Max_Export_Power: 1
        Min_Voltage_Drop: 1.48941590000000001481339495512656867504119873046875
        P_Grid_Max_Export_Power: 7
        Max_Voltage_Drop: 1.0246456999999999926131977190379984676837921142578125
  grid_Output:
    type: "object"
    required:
    - "P_Grid_Export_Output"
    properties:
      P_Grid_Export_Output:
        $ref: "#/definitions/Source"
      Q_Grid_Export_Output:
        $ref: "#/definitions/Source"
      P_Grid_Import_Output:
        $ref: "#/definitions/Source"
      Q_Grid_Import_Output:
        $ref: "#/definitions/Source"
    example:
      P_Grid_Export_Output:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
      Q_Grid_Export_Output:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
      P_Grid_Import_Output:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
      Q_Grid_Import_Output:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
  metaGrid:
    type: "object"
    properties:
      P_Grid_Max_Export_Power:
        type: "integer"
        format: "int32"
      Q_Grid_Max_Export_Power:
        type: "integer"
        format: "int32"
      Max_Voltage_Drop:
        type: "number"
        format: "float"
      Min_Voltage_Drop:
        type: "number"
        format: "float"
    example:
      Q_Grid_Max_Export_Power: 1
      Min_Voltage_Drop: 1.48941590000000001481339495512656867504119873046875
      P_Grid_Max_Export_Power: 7
      Max_Voltage_Drop: 1.0246456999999999926131977190379984676837921142578125
  Source:
    type: "object"
    properties:
      mqtt:
        $ref: "#/definitions/MQTT"
    description: "Selection between MQTT or file mode inputs or outputs"
    example:
      mqtt:
        qos: 0
        host: "host"
        topic: "topic"
  SourceESS:
    type: "object"
    properties:
      mqtt:
        $ref: "#/definitions/MQTT"
      value_percent:
        type: "integer"
        format: "int32"
        minimum: 0
        maximum: 100
    example:
      mqtt:
        qos: 0
        host: "host"
        topic: "topic"
      value_percent: 59
  MQTT:
    type: "object"
    required:
    - "host"
    properties:
      host:
        type: "string"
      topic:
        type: "string"
      qos:
        type: "integer"
        format: "int32"
        minimum: 0
        maximum: 2
    example:
      qos: 0
      host: "host"
      topic: "topic"
  dataset:
    type: "object"
    properties:
      bn:
        type: "string"
      bt:
        type: "integer"
        format: "int64"
      bu:
        type: "string"
      ver:
        type: "integer"
        format: "int64"
      e:
        $ref: "#/definitions/e"
  e:
    type: "object"
    properties:
      t:
        type: "integer"
        format: "int64"
      n:
        type: "string"
      u:
        type: "string"
      v:
        type: "integer"
        format: "int64"
      sv:
        type: "string"
      bv:
        type: "boolean"
  Model:
    type: "object"
    xml:
      name: "Model"
  Model_url:
    type: "object"
    required:
    - "upModelUrl"
    properties:
      upModelUrl:
        type: "string"
    xml:
      name: "ModelUrl"
      wrapped: true
  InputSource:
    type: "object"
    properties:
      load:
        $ref: "#/definitions/Load"
      photovoltaic:
        $ref: "#/definitions/PV"
      ESS:
        $ref: "#/definitions/ESS"
      grid:
        $ref: "#/definitions/grid"
      market:
        $ref: "#/definitions/Source"
    example:
      market:
        mqtt:
          qos: 0
          host: "host"
          topic: "topic"
      load:
        Internal_Forecast: true
        Q_Load:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
        meta:
          pf_Load: 6.02745629999999987802539180847816169261932373046875
        P_Load:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
      ESS:
        SoC_Value:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
          value_percent: 59
        meta:
          ESS_Max_Discharge_Power: 3.61607669999999981058635967201553285121917724609375
          ESS_Max_SoC: 2.30213599999999996015276337857358157634735107421875
          ESS_Charging_Eff: 2.027123000000000008213874025386758148670196533203125
          ESS_Min_SoC: 5.63737699999999986033571985899470746517181396484375
          ESS_Max_Charge_Power: 9.301444000000000045247361413203179836273193359375
          ESS_Discharging_Eff: 4.14560800000000018172841009800322353839874267578125
          ESS_Capacity: 7.06140140000000027242776923230849206447601318359375
      grid:
        meta:
          Q_Grid_Max_Export_Power: 1
          Min_Voltage_Drop: 1.48941590000000001481339495512656867504119873046875
          P_Grid_Max_Export_Power: 7
          Max_Voltage_Drop: 1.0246456999999999926131977190379984676837921142578125
      photovoltaic:
        Internal_Forecast: true
        P_PV:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
        meta:
          PV_Inv_Max_Power: 1
  OutputSource:
    type: "object"
    properties:
      photovoltaic:
        $ref: "#/definitions/PV_Output"
      ESS:
        $ref: "#/definitions/ESS_Output"
      grid:
        $ref: "#/definitions/grid_Output"
    example:
      ESS:
        P_ESS_Output:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
      grid:
        P_Grid_Export_Output:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
        Q_Grid_Export_Output:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
        P_Grid_Import_Output:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
        Q_Grid_Import_Output:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
      photovoltaic:
        Q_PV_Output:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
        P_PV_Output:
          mqtt:
            qos: 0
            host: "host"
            topic: "topic"
  Model_answer:
    type: "object"
    properties:
      models:
        type: "array"
        items:
          $ref: "#/definitions/Model_Output"
    example:
      models:
      - name: "name"
        solver: "solver"
      - name: "name"
        solver: "solver"
  Model_Output:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
      solver:
        type: "string"
    example:
      name: "name"
      solver: "solver"
